### ISSUE TITLE
Gnome-keyring is needed and not provided or hinted at. Skype logs out every time application closes. 

### ISSUE THREAD

**Issue by Barafu** [flathub/com.skype.Client#48] opened 2018-10-11 22:10 UTC
If installation lacks gnome-keyring, (which can happen, for example, in Arch with KDE), then Skype seems to work as intended, except that every time application restarts, it asks for credentials  anew. Installation of `gnome-keyring` via system package manager (and creating default keyring when prompted) seems to solve the problem.
It is completely unobvious for average user. To make things worse, Microsoft support claims that logging out is an intended behavior to force users to update to newer versions. It makes user think that problem is in the flatpak package. 
Please, either provide gnome-keyring in the flatpak package or, if impossible, at least add some script to warn user if gnome-keyring is missing. Not everyone uses Gnome.

**Comment by wjt** [comment] 2018-11-14 15:35
Duplicate of #20.

**Closed** 2018-11-14 20:33 UTC
